### ISSUE TITLE
Create concurrent PIT query based on time data

### ISSUE THREAD

**Issue by por** [transparantnederland/api#7] opened 2016-01-08 11:51 UTC
Dependency: transparantnederland/tnl-open-data#2 and transparantnederland/tnl-open-data#3

concurrent relations:
e.g.:

`/peopleFromOrgsFromPerson` 
with addition
`&timeOverlap=5`

gives all people that have been in network for 5 or more years.

or:

`&concurrent=Off` default is `&concurrent=On`

**Comment by jobspierings** [comment] 2016-01-08 12:50
duplicate of #1

**Closed as completed** 2016-01-19 15:21 UTC
